# Generated by Django 4.0.4 on 2023-02-12 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('active', models.IntegerField(default=0)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher', models.CharField(blank=True, max_length=15, null=True)),
                ('group', models.CharField(blank=True, max_length=10, null=True)),
                ('arm', models.CharField(blank=True, max_length=10, null=True)),
                ('upload', models.IntegerField(default=0)),
                ('lock', models.IntegerField(default=0)),
                ('total_student', models.IntegerField(blank=True, null=True)),
                ('approve_result', models.IntegerField(default=0)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('active', models.IntegerField(default=0)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('keyword', models.SlugField()),
                ('active', models.IntegerField(default=1)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.IntegerField(default=1)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('school_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('school_domain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('anual_result', models.CharField(blank=True, max_length=8, null=True)),
                ('start_result', models.BooleanField(default=False)),
                ('card_usage', models.IntegerField(default=5)),
                ('student_unique', models.IntegerField(blank=True, null=True)),
                ('staff_unique', models.IntegerField(blank=True, null=True)),
                ('use_hostel', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.IntegerField(default=1)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm', models.CharField(max_length=10)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('arm', models.CharField(max_length=10)),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('CA_max', models.IntegerField(default=40)),
                ('exam_max', models.IntegerField(default=60)),
                ('number_of_subjects', models.IntegerField(blank=True, null=True)),
                ('number_of_student', models.IntegerField(blank=True, null=True)),
                ('lock', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('approve_result', models.IntegerField(default=0)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
