# Generated by Django 4.0.4 on 2023-02-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='school_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='use_hostel',
            field=models.BooleanField(default=True),
        ),
    ]
