# Generated by Django 4.0.4 on 2023-05-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_config_school_address_alter_config_use_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='allclass',
            name='access',
            field=models.CharField(default='435453454', max_length=100),
            preserve_default=False,
        ),
    ]
