# Generated by Django 4.0.4 on 2023-05-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_allclass_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allclass',
            options={'ordering': ['group', 'arm']},
        ),
    ]
