# Generated by Django 4.0.4 on 2023-10-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_config_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='parent_unique',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
