# Generated by Django 4.0.4 on 2023-10-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_config_parent_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default='345', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(default='543', max_length=3),
            preserve_default=False,
        ),
    ]
