# Generated by Django 4.0.4 on 2023-11-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_class_code_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
