# Generated by Django 4.0.4 on 2023-11-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='allclass',
            name='promotion_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
