# Generated by Django 4.0.4 on 2023-11-22 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_registeredsubjects_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredsubjects',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
