# Generated by Django 4.0.4 on 2023-11-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_registeredsubjects_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredsubjects',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredsubjects',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
