# Generated by Django 4.0.4 on 2023-11-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_registeredsubjects_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allclass',
            name='category',
            field=models.CharField(default='junior', max_length=10),
            preserve_default=False,
        ),
    ]
