# Generated by Django 4.0.4 on 2023-12-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_allclass_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredsubjects',
            name='category',
            field=models.CharField(default='senior', max_length=10),
            preserve_default=False,
        ),
    ]
