# Generated by Django 4.0.4 on 2023-12-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_registeredsubjects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='allclass',
            name='class_teacher_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='allclass',
            name='class_teacher_signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='allclass',
            name='overall_approval',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
