# Generated by Django 4.0.4 on 2023-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_allclass_class_teacher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allclass',
            name='class_teacher_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature'),
        ),
    ]
