# Generated by Django 4.0.4 on 2022-11-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created']},
        ),
    ]
