# Generated by Django 4.0.4 on 2023-02-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='sms',
            field=models.BooleanField(default=False),
        ),
    ]
