# Generated by Django 4.0.4 on 2023-11-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_dashboard_news_email_news_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
