# Generated by Django 4.0.4 on 2023-01-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='first_install',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='second_install',
        ),
    ]
