# Generated by Django 4.0.4 on 2023-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_first_install_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(default='Others', max_length=100),
            preserve_default=False,
        ),
    ]
