# Generated by Django 4.0.4 on 2023-02-11 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
