# Generated by Django 4.0.4 on 2023-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='arm',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.CharField(default='JS1', max_length=10),
            preserve_default=False,
        ),
    ]
