# Generated by Django 4.0.4 on 2023-02-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_arm_payment_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='arm',
        ),
    ]
