# Generated by Django 4.0.4 on 2022-12-23 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('other_name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.TextField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('registration_number', models.CharField(max_length=255)),
                ('active', models.IntegerField(default=1)),
                ('passport', models.ImageField(default='passport.jpg', upload_to='teacher_passport')),
                ('nok_relationship', models.CharField(max_length=10)),
                ('nok_full_name', models.CharField(max_length=100)),
                ('nok_address', models.TextField(max_length=150)),
                ('nok_mobile', models.CharField(max_length=15)),
                ('nok_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instangram', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
