# Generated by Django 4.0.4 on 2023-02-12 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
