# Generated by Django 4.0.4 on 2023-05-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='other_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
