# Generated by Django 4.0.4 on 2023-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_day_staff_month_staff_year_alter_staff_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='day',
            new_name='birth_day',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='month',
            new_name='birth_month',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='year',
            new_name='birth_year',
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(),
        ),
    ]
