# Generated by Django 4.0.4 on 2023-11-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_day_staff_birth_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nok_title',
            field=models.CharField(default='Mr', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nok_address',
            field=models.CharField(max_length=150),
        ),
    ]
