# Generated by Django 4.0.4 on 2023-12-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staff_nok_title_alter_staff_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='complete_registration',
            field=models.BooleanField(default=False),
        ),
    ]
