# Generated by Django 4.0.4 on 2023-02-11 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_bedspace_added_by_alter_floor_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid_occupant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paid_occupant',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
