# Generated by Django 4.0.4 on 2022-12-23 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('usage', models.IntegerField(default=0)),
                ('student', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=5, null=True)),
                ('arm', models.CharField(blank=True, max_length=5, null=True)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
