# Generated by Django 4.0.4 on 2023-02-11 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
