# Generated by Django 4.0.4 on 2023-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='arm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='group',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
