# Generated by Django 4.0.4 on 2022-12-23 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Deleted',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CA1', models.IntegerField(blank=True, default=0, null=True)),
                ('CA2', models.IntegerField(blank=True, default=0, null=True)),
                ('CA3', models.IntegerField(blank=True, default=0, null=True)),
                ('project', models.IntegerField(blank=True, default=0, null=True)),
                ('test', models.IntegerField(blank=True, default=0, null=True)),
                ('exam', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('average', models.IntegerField(blank=True, default=0, null=True)),
                ('grade', models.CharField(blank=True, max_length=15, null=True)),
                ('remark', models.CharField(blank=True, max_length=15, null=True)),
                ('position', models.CharField(blank=True, max_length=3, null=True)),
                ('group', models.CharField(max_length=5)),
                ('arm', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=20)),
                ('term', models.IntegerField()),
                ('student', models.CharField(max_length=255)),
                ('lock', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.IntegerField(blank=True, default=1, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CA1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('CA2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('CA3', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('project', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('test', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('exam', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=15, null=True)),
                ('remark', models.CharField(blank=True, max_length=15, null=True)),
                ('position', models.CharField(blank=True, max_length=3, null=True)),
                ('group', models.CharField(max_length=5)),
                ('arm', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=20)),
                ('term', models.IntegerField()),
                ('student', models.CharField(max_length=255)),
                ('lock', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.IntegerField(blank=True, default=1, null=True)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
