# Generated by Django 4.0.4 on 2023-10-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_record_ref_record_deleted_ref_alter_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
