# Generated by Django 4.0.4 on 2023-11-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_record_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
