# Generated by Django 4.0.4 on 2023-11-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_record_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
