# Generated by Django 4.0.4 on 2023-12-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_record_average_alter_record_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='arm',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='group',
            field=models.CharField(max_length=10),
        ),
    ]
