# Generated by Django 4.0.4 on 2023-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_record_arm_alter_record_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='position',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
