# Generated by Django 4.0.4 on 2023-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_record_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
