# Generated by Django 4.0.4 on 2024-05-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_record_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='annaul_average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
