# Generated by Django 4.0.4 on 2023-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='passport',
            field=models.ImageField(default='passport.jpg', upload_to='parent_passport'),
        ),
    ]
