# Generated by Django 4.0.4 on 2023-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_alter_parent_passport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='instangram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='registration_number',
            new_name='unique_number',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='nok_address',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='nok_email',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='nok_full_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='nok_mobile',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='nok_relationship',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='sex',
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
