# Generated by Django 4.0.4 on 2023-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_remove_parent_address_remove_parent_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='title',
            field=models.CharField(default='Mr', max_length=10),
            preserve_default=False,
        ),
    ]
