# Generated by Django 4.0.4 on 2023-10-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_parent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.TextField(default='No 34 benin auchi road, benin', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
