# Generated by Django 4.0.4 on 2023-10-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0006_parent_address_alter_parent_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
