# Generated by Django 4.0.4 on 2023-05-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
