# Generated by Django 4.0.4 on 2023-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_profile_blocked_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='set_password',
            field=models.BooleanField(default=True),
        ),
    ]
