# Generated by Django 4.0.4 on 2022-12-23 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('other_name', models.CharField(max_length=20)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('level', models.IntegerField(default=0)),
                ('group', models.CharField(blank=True, max_length=5, null=True)),
                ('arm', models.CharField(blank=True, max_length=5, null=True)),
                ('active', models.IntegerField(default=1)),
                ('passport', models.ImageField(default='passport.jpg', upload_to='passport')),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nok_address', models.TextField(blank=True, max_length=150, null=True)),
                ('nok_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('nok_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lock', models.IntegerField(default=0)),
                ('graduated', models.BooleanField(default=False)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paid_Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student', models.CharField(max_length=255)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ref', models.CharField(max_length=200)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('group', models.CharField(blank=True, max_length=5, null=True)),
                ('arm', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.IntegerField(default=1)),
                ('installment', models.IntegerField(blank=True, null=True)),
                ('print', models.IntegerField(default=1)),
                ('paid_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
