# Generated by Django 4.0.4 on 2023-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_ref_alter_paid_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_student',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
