# Generated by Django 4.0.4 on 2023-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_paid_student_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='instangram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
