# Generated by Django 4.0.4 on 2023-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_facebook_student_instangram_student_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='other_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
