# Generated by Django 4.0.4 on 2023-10-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_instangram_student_instagram_student_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentguardian',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentguardian'),
        ),
    ]
