# Generated by Django 4.0.4 on 2023-10-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentguardian',
            name='passport',
            field=models.ImageField(default='passport.jpg', upload_to='parent'),
        ),
    ]
