# Generated by Django 4.0.4 on 2023-10-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentguardian_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentguardian',
            name='active',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='instangram',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='studentguardian',
            name='unique_number',
        ),
    ]
