# Generated by Django 4.0.4 on 2023-10-27 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0010_remove_studentguardian_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentguardian',
            name='added_by',
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
