# Generated by Django 4.0.4 on 2023-11-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_guardian_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(default='junior', max_length=10),
            preserve_default=False,
        ),
    ]
