# Generated by Django 4.0.4 on 2023-11-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_student_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='arm',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
