# Generated by Django 4.0.4 on 2023-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_student_day_student_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='day',
            new_name='birth_day',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='month',
            new_name='birth_month',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
