# Generated by Django 4.0.4 on 2023-11-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_rename_day_student_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['registration_number']},
        ),
    ]
