# Generated by Django 4.0.4 on 2023-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='register_course',
            field=models.BooleanField(default=False),
        ),
    ]
