# Generated by Django 4.0.4 on 2022-12-23 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('teacher', models.CharField(max_length=10)),
                ('lock', models.IntegerField(default=0)),
                ('group', models.CharField(blank=True, max_length=5, null=True)),
                ('arm', models.CharField(blank=True, max_length=5, null=True)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
