# Generated by Django 4.0.4 on 2023-12-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='arm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
