# Generated by Django 4.0.4 on 2022-12-23 15:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('other_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('group', models.CharField(default='JS1', max_length=5)),
                ('arm', models.CharField(max_length=5)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
                ('added_by', models.CharField(max_length=100)),
                ('paid_on', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paid_Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('ref', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('term', models.CharField(blank=True, max_length=5, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('cleared_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
