# Generated by Django 4.0.4 on 2022-12-23 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0002_alter_applicant_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='paid_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
