# Generated by Django 4.0.4 on 2023-02-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_applicant_ref_alter_applicant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paid_applicant',
            old_name='amount_paid',
            new_name='amount',
        ),
    ]
