# Generated by Django 4.0.4 on 2023-05-09 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0007_paid_applicant_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_applicant',
            name='manual_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paid_applicant',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
