# Generated by Django 4.0.4 on 2023-05-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_paid_applicant_manual_cleared_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paid_applicant',
            old_name='cleared_by',
            new_name='approved_by',
        ),
    ]
