# Generated by Django 4.0.4 on 2023-05-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_rename_cleared_by_paid_applicant_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid_applicant',
            name='approved_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
