# Generated by Django 4.0.4 on 2023-05-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0011_alter_paid_applicant_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paid_applicant',
            old_name='approved_by',
            new_name='cleared_by',
        ),
    ]
