# Generated by Django 4.0.4 on 2023-11-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0012_rename_approved_by_paid_applicant_cleared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_applicant',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.applicant'),
            preserve_default=False,
        ),
    ]
