# Generated by Django 4.0.4 on 2023-11-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0013_paid_applicant_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='category',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
