# Generated by Django 4.0.4 on 2023-11-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0014_applicant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
