# Generated by Django 4.0.4 on 2023-11-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0015_alter_applicant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='arm',
            field=models.CharField(max_length=10),
        ),
    ]
