# Generated by Django 4.0.4 on 2024-08-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0016_alter_applicant_arm'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='appicant_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
