# Generated by Django 4.0.4 on 2024-08-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0017_applicant_appicant_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='appicant_number',
            new_name='applicant_number',
        ),
    ]
