# Generated by Django 4.0.4 on 2024-11-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0019_applicant_active_applicant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='registered',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
