# Generated by Django 4.0.4 on 2024-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0020_applicant_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
