# Generated by Django 4.0.4 on 2024-11-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0021_alter_applicant_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='active',
        ),
    ]
