# Generated by Django 4.0.4 on 2024-11-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0022_remove_applicant_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passport',
            field=models.ImageField(blank=True, default='passport.jpg', null=True, upload_to='passport'),
        ),
    ]
