# Generated by Django 4.0.4 on 2024-11-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0023_applicant_active_alter_applicant_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
